<a href="https://colab.research.google.com/github/WaldekCh/machine_learning_krakowiak/blob/main/supervised/01_basics/01_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import pandas as pd
import numpy as np
import sklearn
import time

In [31]:
sklearn.__version__

'1.0.1'

In [32]:

data = {
    'size': ['XL', 'L', 'M', 'L', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red'],
    'gender': ['female', 'male', 'male', 'female', 'female'],
    'price': [199.0, 89.0, 99.0, 129.0, 79.0],
    'weight': [500, 450, 300, 380, 410],
    'bought': ['yes', 'no', 'yes', 'no', 'yes']
}

df_raw = pd.DataFrame(data=data)
df_raw



size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

In [33]:
df =df_raw.copy()
df.info(
  
)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   size    5 non-null      object 
 1   color   5 non-null      object 
 2   gender  5 non-null      object 
 3   price   5 non-null      float64
 4   weight  5 non-null      int64  
 5   bought  5 non-null      object 
dtypes: float64(1), int64(1), object(4)
memory usage: 368.0+ bytes


In [34]:
df[['size','color','gender','bought']]=df[['size','color','gender','bought']].astype('category')

In [35]:
df.weight=df.weight.astype('float')

In [36]:
df.dtypes

size      category
color     category
gender    category
price      float64
weight     float64
bought    category
dtype: object

In [37]:
df.describe(include=['category']).transpose()

count unique     top freq
size       5      3       M    2
color      5      3     red    2
gender     5      2  female    3
bought     5      2     yes    3

In [38]:
df.describe().T

count   mean        std    min    25%    50%    75%    max
price     5.0  119.0  48.476799   79.0   89.0   99.0  129.0  199.0
weight    5.0  408.0  75.299402  300.0  380.0  410.0  450.0  500.0

In [39]:
df


size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

In [40]:
from sklearn.preprocessing import LabelEncoder

le= LabelEncoder()
le.fit(df['bought'])
le.transform(df['bought'])

array([1, 0, 1, 0, 1])

In [41]:
le.fit_transform(df['bought'])

array([1, 0, 1, 0, 1])

In [42]:
le.classes_

array(['no', 'yes'], dtype=object)

In [43]:
df['bought'] = le.fit_transform(df['bought'])

In [44]:
le.inverse_transform(df.bought)


array(['yes', 'no', 'yes', 'no', 'yes'], dtype=object)

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64 
 4   weight  5 non-null      float64 
 5   bought  5 non-null      int64   
dtypes: category(3), float64(2), int64(1)
memory usage: 567.0 bytes


In [46]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse =False,drop='first')
encoder.fit(df[['size']])

OneHotEncoder(drop='first', sparse=False)

In [47]:
encoder.transform(df[['size']])

array([[0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.]])

In [48]:
pd.get_dummies(df,drop_first= True)

price  weight  bought  size_M  size_XL  color_green  color_red  gender_male
0  199.0   500.0       1       0        1            0          1            0
1   89.0   450.0       0       0        0            1          0            1
2   99.0   300.0       1       1        0            0          0            1
3  129.0   380.0       0       0        0            1          0            0
4   79.0   410.0       1       1        0            0          1            0

In [49]:
from sklearn.preprocessing import scale

In [50]:
scale(df.price)

array([ 1.84506242, -0.69189841, -0.4612656 ,  0.2306328 , -0.92253121])

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64 
 4   weight  5 non-null      float64 
 5   bought  5 non-null      int64   
dtypes: category(3), float64(2), int64(1)
memory usage: 567.0 bytes


In [57]:
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
df[['price','weight']] = scaler.fit_transform(df[['price','weight']])
df

size  color  gender     price    weight  bought
0   XL    red  female  1.845062  1.366002       1
1    L  green    male -0.691898  0.623610       0
2    M   blue    male -0.461266 -1.603567       1
3    L  green  female  0.230633 -0.415740       0
4    M    red  female -0.922531  0.029696       1

<bound method Series.unique of 0    1.845062
1   -0.691898
2   -0.461266
3    0.230633
4   -0.922531
Name: price, dtype: float64>

In [59]:
df = pd.get_dummies(data=df,drop_first=True)


In [60]:
df


price    weight  bought  ...  color_green  color_red  gender_male
0  1.845062  1.366002       1  ...            0          1            0
1 -0.691898  0.623610       0  ...            1          0            1
2 -0.461266 -1.603567       1  ...            0          0            1
3  0.230633 -0.415740       0  ...            1          0            0
4 -0.922531  0.029696       1  ...            0          1            0

[5 rows x 8 columns]